# Use container system
sudo: false

# Cache pip & libsodium
cache:
  directories:
  - $HOME/libsodium
  - $HOME/.cache/pip

# Clean up pip log
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

# Build matrix
language: python
matrix:
  include:
  - python: "3.4"
    env:
    - EVENT_LOOP=asyncio
    - TIMEOUT=2.0
    - IGNORE=tests/test_cli.py
  - python: "3.5"
    env:
    - EVENT_LOOP=asyncio
    - TIMEOUT=2.0
  - python: "3.5"
    env:
    - EVENT_LOOP=uvloop
    - TIMEOUT=2.0
    before_script: "pip install .[uvloop]"
  - python: "3.6"
    env:
    - EVENT_LOOP=asyncio
    - TIMEOUT=2.0
  - python: "3.6"
    env:
    - EVENT_LOOP=uvloop
    - TIMEOUT=2.0
    before_script: "pip install .[uvloop]"
# TODO: Enable once 3.7 support has been added
#  - python: "3.7"
#    env:
#    - EVENT_LOOP=asyncio
#    - TIMEOUT=2.0
#  - python: "3.7"
#    env:
#    - EVENT_LOOP=uvloop
#    - TIMEOUT=2.0
#    before_script: "pip install .[uvloop]"
  - python: "pypy3"  # 2017-08-05: It's pypy3-5.8.0-beta
    env:
    - EVENT_LOOP=asyncio
    - TIMEOUT=16.0
# TODO: Re-enable once pypy3 is able to compile uvloop
#  - python: "pypy3"  # 2017-08-05: It's pypy3-5.8.0-beta
#    env:
#      - EVENT_LOOP=uvloop
#      - TIMEOUT=16.0
#    before_script: "pip install .[uvloop]"

# Install dependencies
before_install:
  - ./.travis-install-libsodium.sh
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HOME}/libsodium/lib
install:
  - pip install -U setuptools pip
  - "pip install .[dev]"
  - pip install codecov

# Run flake8, isort, check docs & tests
# TODO: Re-enable isort once #85 has been resolved
script:
  - >
    if [[ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]]; then
      flake8 . || travis_terminate 1;
      #isort -rc -c . || (isort -rc -df . && return 1) || travis_terminate 1;
    fi
  - python setup.py checkdocs
  - >
    py.test \
      --ignore=$IGNORE \
      --cov-config .coveragerc \
      --cov=saltyrtc.server \
      --loop=$EVENT_LOOP \
      --timeout=$TIMEOUT

# After success
after_success:
  - codecov

